// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"book/service/search/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/search/do",
					Handler: searchHandler(serverCtx),
				},
			}...,
		),
	)
}
