// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Id string `json:"id"`
}

type SearchReply struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Message string `json:"message"`
}
